# Dirichlet Distribution

## In Tensorflow :D

In [1]:
import tensorflow as tf
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

distribution_name = "Dirichlet"

### Mathematical Details:

The Dirichlet is a distribution over the open (k-1)-simplex, i.e.,

*S^{k-1} = { (x_0, ..., x_{k-1}) in R^k : sum_j x_j = 1 and all_j x_j > 0 }.*


The probability density function (pdf) is,

*pdf(x; alpha) = prod_j x_j^(alpha_j - 1) / Z
Z = prod_j Gamma(alpha_j) / Gamma(sum_j alpha_j)*

where:

 - x in S^{k-1}, i.e., the (k-1)-simplex,
 - concentration = alpha = [alpha_0, ..., alpha_{k-1}], alpha_j > 0,
 - Z is the normalization constant aka the multivariate beta function, and,
 - Gamma is the gamma function.

The concentration represents mean total counts of class occurrence, i.e.,

*concentration = alpha = mean * total_concentration*

where mean in S^{k-1} and total_concentration is a positive real number representing a mean total count.



In [2]:
#Define the distribution
dist = tf.contrib.distributions.Dirichlet(alpha=[1.0,2.0,3.0])

In [3]:
#Generate a sample given shape. Could be two observations with 5 features.
randomSample = dist.sample([2,5])

#Generate a 'massive' sample for plotting
massiveSampling = dist.sample([10000])

In [4]:
with tf.Session() as sess:
    
    _randomSample,_massiveSample = sess.run([randomSample,massiveSampling])

### Output of random values from distribution

In [5]:
print('2 observations x 5 features:\n%s' % _randomSample)

2 observations x 5 features:
[[[ 0.06790281  0.64318728  0.28890985]
  [ 0.00188693  0.9322859   0.06582713]
  [ 0.0403049   0.48315117  0.47654396]
  [ 0.21812643  0.09863134  0.6832422 ]
  [ 0.24709734  0.39487651  0.35802612]]

 [[ 0.16185987  0.47562408  0.36251602]
  [ 0.16521324  0.44139642  0.39339039]
  [ 0.28837675  0.0831795   0.62844378]
  [ 0.00359853  0.36453843  0.63186306]
  [ 0.01027645  0.13307072  0.85665286]]]
