# Multinomial Distribution

## In Tensorflow :D

In [1]:
import tensorflow as tf
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

distribution_name = "Multinomial"

### Mathematical Details:

The Multinomial is a distribution over k-class counts, i.e., a length-k vector of non-negative integer counts = n = [n_0, ..., n_{k-1}].

The probability mass function (pmf) is,

*pmf(n; pi, N) = prod_j (pi_j)^n_j / Z<br>
Z = (prod_j n_j!) / N!*

where: probs = pi = [pi_0, ..., pi_{k-1}], pi_j > 0, sum_j pi_j = 1, total_count = N, N a positive integer, Z is the normalization constant, and, N! denotes N factorial.



In [8]:
#Define the distribution
dist = tf.contrib.distributions.Multinomial(n=10.0,p=[0.2,0.3,0.5])

In [9]:
#Generate a sample given shape. Could be two observations with 5 features.
randomSample = dist.sample([2,5])

#Generate a 'massive' sample for plotting
massiveSampling = dist.sample([10000])

In [10]:
with tf.Session() as sess:
    
    _randomSample,_massiveSample = sess.run([randomSample,massiveSampling])

### Output of random values from distribution

In [11]:
print('2 observations x 5 features:\n%s' % _randomSample)

2 observations x 5 features:
[[[ 1.  5.  4.]
  [ 3.  1.  6.]
  [ 1.  2.  7.]
  [ 2.  1.  7.]
  [ 0.  4.  6.]]

 [[ 4.  3.  3.]
  [ 4.  2.  4.]
  [ 5.  1.  4.]
  [ 3.  3.  4.]
  [ 2.  1.  7.]]]
