In [14]:
import numpy as np
import tensorflow as tf

In [27]:
dirichlet = tf.contrib.distributions.Dirichlet(alpha=[1.0,2.0,3.0]) #Like dirichlet

#### Step 1: Draw a vector of probabilities from the Dirichlet distribution

In [28]:
dirichletSample = dirichlet.sample(1)

#### Step 2: Use the vector of probabilities to draw a vector of outcomes from the multinomial distribution

In [29]:
multinomial = tf.contrib.distributions.Multinomial(n=1.0,p=dirichletSample)

In [30]:
multinomialSample = multinomial.sample(10)

In [31]:
with tf.Session() as sess:
    
    _multinomialSample,_dirichletSample = sess.run([multinomialSample,dirichletSample])

In [32]:
print('From Dirichlet sample:\n%s' % _dirichletSample)

print('Generated outcomes from Multinomial:\n %s' % _multinomialSample)

From Dirichlet sample:
[[ 0.00896624  0.40878019  0.58225358]]
Generated outcomes from Multinomial:
 [[[ 0.  0.  1.]]

 [[ 0.  0.  1.]]

 [[ 0.  0.  1.]]

 [[ 0.  1.  0.]]

 [[ 0.  0.  1.]]

 [[ 0.  0.  1.]]

 [[ 0.  0.  1.]]

 [[ 0.  1.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  1.  0.]]]
