In [1]:
import numpy as np
import tensorflow as tf

In [2]:
beta = tf.contrib.distributions.Beta(a=1.0,b=1.0) #Like dirichlet

#### Step 1: Draw a vector of probabilities from the Beta distribution

In [3]:
betaSample = beta.sample(3)

#### Step 2: Use the vector of probabilities to draw a vector of outcomes from the Bernoulli distribution

In [4]:
bernoulli = tf.contrib.distributions.Bernoulli(p=betaSample)

In [5]:
bernoulliSample = bernoulli.sample(10)

In [6]:
with tf.Session() as sess:
    
    _bernoulliSample,_betaSample = sess.run([bernoulliSample,betaSample])

In [7]:
print('From beta sample:\n%s' % _betaSample)

print('Generated outcomes from Bernoulli:\n %s' % _bernoulliSample)

From beta sample:
[ 0.73856419  0.2892524   0.64826411]
Generated outcomes from Bernoulli:
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]
 [1 0 1]
 [0 0 0]
 [1 0 0]
 [1 0 1]]
