# Gather

## In Tensorflow :D

In [1]:
import tensorflow as tf
import numpy as np

### 2D data

In [2]:
data = np.arange(2*3).reshape(2,3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
dummy_ph = tf.placeholder(dtype=tf.int32,shape=[2,3])

In [22]:
gather0 = tf.gather(params=dummy_ph,indices=0)

In [23]:
with tf.Session() as sess:
    
    results = sess.run(fetches=[gather0],feed_dict={dummy_ph : data})
    _gather0 = np.array(results[0])


In [24]:
_gather0

array([0, 1, 2])

### 3D data

In [25]:
data = np.arange(2*3*4).reshape(2,3,4)
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
dummy_ph = tf.placeholder(dtype=tf.int32,shape=[2,3,4])

In [83]:
gather0 = tf.gather(params=dummy_ph,indices=0)
gather1 = tf.gather(params=dummy_ph,indices=1)


In [84]:
with tf.Session() as sess:
    
    results = sess.run(fetches=[gather0,gather1],feed_dict={dummy_ph : data})
    _gather0 = np.array(results[0])
    _gather1 = np.array(results[1])

In [85]:
_gather0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
_gather1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])