# Softmax Cross Entropy With Logits

## In Tensorflow :D

In [1]:
import tensorflow as tf
import numpy as np

## Softmax cross entropy with logits

### Data

In [322]:
batch_size = 5
num_classes = 3

labels = np.array([1,0,0,1,0,0,1,0,0,1,0,0,1,0,0],dtype=np.float32).reshape(batch_size,num_classes)

logits = np.array(np.random.normal(size=batch_size*num_classes)).reshape(batch_size,num_classes)


In [323]:
labels

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32)

In [324]:
logits

array([[-0.08429715,  0.97495748, -0.20417905],
       [-0.76305238,  1.84650688,  1.28349857],
       [-1.43091644,  0.94795309, -0.12870057],
       [-1.33148967, -1.70622505, -1.03939716],
       [ 1.70010804, -0.18659773,  0.33124405]])

In [325]:
loss = tf.nn.softmax_cross_entropy_with_logits(labels=labels,logits=logits)

In [326]:
with tf.Session() as sess:
    
    results = sess.run(fetches=[loss])
    _loss = np.array(results[0])


In [327]:
_loss

array([ 1.56260739,  3.10611976,  2.73891116,  1.10747228,  0.34072467])