# Unstack vs Transpose

## In Tensorflow :D

In [1]:
import tensorflow as tf
import numpy as np

### 2D data

In [2]:
data = np.arange(2*3).reshape(2,3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
dummy_ph = tf.placeholder(dtype=tf.int32,shape=[2,3])

In [4]:
unstacked0 = tf.unstack(value=dummy_ph,axis=1)

transposed0 = tf.transpose(a=dummy_ph,perm=[1,0])

In [5]:
with tf.Session() as sess:
    
    results = sess.run(fetches=[unstacked0,transposed0],feed_dict={dummy_ph : data})
    _unstack0 = np.array(results[0])
    _trans0 = np.array(results[1])


In [6]:
_unstack0

array([[0, 3],
       [1, 4],
       [2, 5]])

In [7]:
_trans0

array([[0, 3],
       [1, 4],
       [2, 5]])

### 3D Data

In [8]:
data = np.arange(2*3*4).reshape(2,3,4)
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
dummy_ph = tf.placeholder(dtype=tf.int32,shape=[2,3,4])

In [10]:
unstacked0 = tf.unstack(value=dummy_ph,axis=1)
transposed0 = tf.transpose(a=dummy_ph,perm=[1,0,2])

In [11]:
with tf.Session() as sess:
    
    results = sess.run(fetches=[unstacked0,transposed0],feed_dict={dummy_ph : data})
    _unstack0 = np.array(results[0])
    _trans0 = np.array(results[1])


In [12]:
_unstack0

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [13]:
_trans0

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [14]:
unstacked1 = tf.unstack(value=dummy_ph,axis=2)
transposed1 = tf.transpose(a=dummy_ph,perm=[2,0,1])

In [15]:
with tf.Session() as sess:
    
    results = sess.run(fetches=[unstacked1,transposed1],feed_dict={dummy_ph : data})
    _unstack1 = np.array(results[0])
    _trans1 = np.array(results[1])

In [16]:
_unstack1

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [17]:
_trans1

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])